"""Create by user in questionneire

Revision ID: 301b2ef6de61
Revises: 9757357c898c
Create Date: 2025-08-13 15:45:53.074049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301b2ef6de61'
down_revision: Union[str, None] = '9757357c898c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'questionnaires', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionnaires', type_='foreignkey')
    op.drop_column('questionnaires', 'created_by_id')
    # ### end Alembic commands ###
