# Generated by Django 5.0.14 on 2025-05-07 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.EmailField(default='', max_length=254, unique=True)),
                ('Email', models.CharField(default='', max_length=150)),
                ('Age', models.IntegerField(default=0)),
            ],
        ),
    ]
